export const cards = [
  {
    id: 1,
    workout: "Отжимания",
    times: 17,
    sets: 4,
    weight: 0,
    day: "Понедельник",
  },
  {
    id: 2,
    workout: "Отжимания со скамьи",
    times: 15,
    sets: 4,
    weight: 20,
    day: "Понедельник",
  },
  {
    id: 3,
    workout: "Разведение",
    times: 17,
    sets: 4,
    weight: 5,
    day: "Понедельник",
  },
  { id: 4, workout: "Молоток", times: 13, sets: 4, weight: 8, day: "Вторник" },
  {
    id: 5,
    workout: "Тяга к подбородку",
    times: 16,
    sets: 4,
    weight: 22.5,
    day: "Вторник",
  },
  {
    id: 6,
    workout: "Подтягивания",
    times: 6,
    sets: 4,
    weight: 0,
    day: "Вторник",
  },
  {
    id: 6,
    workout: "Тяга в наклоне",
    times: 12,
    sets: 4,
    weight: 22,
    day: "Вторник",
  },
  { id: 7, workout: "Молоток", times: 13, sets: 4, weight: 8, day: "Пятница" },
  {
    id: 8,
    workout: "Тяга к подбородку",
    times: 16,
    sets: 4,
    weight: 22.5,
    day: "Пятница",
  },
  {
    id: 9,
    workout: "Подтягивания",
    times: 6,
    sets: 4,
    weight: 0,
    day: "Пятница",
  },
  {
    id: 10,
    workout: "Тяга в наклоне",
    times: 12,
    sets: 4,
    weight: 22,
    day: "Пятница",
  },
  {
    id: 11,
    workout: "Присед",
    times: 18,
    sets: 4,
    weight: 0,
    day: "Среда",
  },
  {
    id: 12,
    workout: "Выпады",
    times: 18,
    sets: 4,
    weight: 0,
    day: "Среда",
  },
  {
    id: 12,
    workout: "Выпады",
    times: 18,
    sets: 4,
    weight: 0,
    day: "Среда",
  },
  {
    id: 13,
    workout: "Отжимания",
    times: 13,
    sets: 4,
    weight: 0,
    day: "Четверг",
  },
  {
    id: 14,
    workout: "Жим лёжа",
    times: 18,
    sets: 4,
    weight: 22.5,
    day: "Четверг",
  },
  {
    id: 15,
    workout: "Брусья",
    times: 6,
    sets: 4,
    weight: 0,
    day: "Четверг",
  },
  {
    id: 16,
    workout: "Отжимания со скамьи",
    times: 15,
    sets: 4,
    weight: 0,
    day: "Четверг",
  },
  {
    id: 17,
    workout: "Разведение",
    times: 17,
    sets: 4,
    weight: 5,
    day: "Четверг",
  },
  {
    id: 18,
    workout: "Подъём",
    times: 'MAX',
    sets: 4,
    weight: 0,
    day: "Понедельник",
  },
  {
    id: 19,
    workout: "Подъём",
    times: 'MAX',
    sets: 4,
    weight: 0,
    day: "Вторник",
  },
  {
    id: 20,
    workout: "Подъём",
    times: 'MAX',
    sets: 4,
    weight: 0,
    day: "Среда",
  },
  {
    id: 21,
    workout: "Подъём",
    times: 'MAX',
    sets: 4,
    weight: 0,
    day: "Четверг",
  },
  {
    id: 22,
    workout: "Подъём",
    times: 'MAX',
    sets: 4,
    weight: 0,
    day: "Пятница",
  },

];
